services:
  web-api:
    container_name: corebankingapp-web-api
    build:
      context: .
      dockerfile: src/AuthService.Api/Dockerfile
    ports:
      - 5003:8080
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Server=postgres;Port=5432;Database=postgres;User Id=c-postgres;Password=postgres;     

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: c-postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    # volumes:
    #   - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command: postgres -c listen_addresses='*' -p 5432

  # seq:
  #   image: datalust/seq:2024.3
  #   container_name: seq
  #   environment:
  #     - ACCEPT_EULA=Y
  #   ports:
  #     - 8081:80
